### ISSUE TITLE
Game crashes when saving after first level

### ISSUE THREAD

**Issue by Silicomancer** [HurricanGame/Hurrican#36]
I played the game (latest flatpak) on Kubuntu 22.04 using keyboard. When finishing the first level, a list of empty entries for game saving appeared. I pressed the Return key to save the game. The game crashed which means it disappeared immediately without any error message.

This is the end of the game log:

```
-> Load Level : jungle.map successful ! <-

Loaded song file /app/share/hurrican//data/music/JungleBeats.it
Loaded song file /app/share/hurrican//data/music/boss_robofist.it
save games loaded
save games loaded
save games loaded
save games loaded
save games loaded
save games loaded
save games loaded
save games loaded
save games loaded
save games loaded

```

**Comment by drfiemost** [comment]
Hard to tell without a backtrace. Even if the save location is read only it should not crash.
Can you check the "Using save path" from the log?

**Comment by Silicomancer** [comment]
Sure, I am glad to help:

```
--> Using external config path '/home/myusername/.var/app/io.github.hurricangame.hurrican/config/hurrican' <--
--> Using external storage path '/app/share/hurrican/' <--
--> Using save path '/home/myusername/.var/app/io.github.hurricangame.hurrican/data/hurrican' <--
```

The save path does exist. And it contains only one file named "Hurrican.hsl" (size 480 byte).

Is there a way to get the backtrace?

**Comment by drfiemost** [comment]
You should run the app through gdb then use the `bt` command to print a backtrace after the crash, instructions here: https://docs.flatpak.org/en/latest/debugging.html

It would be very useful, I'm not able to reproduce the crash.

**Comment by Silicomancer** [comment]
```
flatpak run --command=sh --devel io.github.hurricangame.hurrican
Error: runtime/org.freedesktop.Sdk/x86_64/22.08 is not installed

```
I guess I need to install that SDK first? Like this?

`flatpak install flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08`

**Comment by drfiemost** [comment]
Yes, it includes gdb among other things. I think you also need to install the hurrican .Debug package.

**Comment by Silicomancer** [comment]
Still something wrong:

`flatpak install flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08`
Succeeded.

`flatpak install flathub io.github.hurricangame.hurrican.Debug`


flatpak run --command=sh --devel io.github.hurricangame.hurrican.Debug
bwrap: execvp sh: No such file or directory

**Comment by drfiemost** [comment]
Yes thanks! I can see the problem now, will hopefully push a fix over the weekend.

BTW the debug package only contains debugging symbols, it's not an executable.

**Comment by drfiemost** [comment]
Fixed!
@Silicomancer thanks for taking the time debugging the issue
@thrimbor can you please update the flatpack build?

**Comment by thrimbor** [comment]
Done.

**Comment by Silicomancer** [comment]
Works for me now. Thank you!
