### ISSUE TITLE
Lighter CRT filter? (As previously)

### ISSUE THREAD

**Issue by vanfanel** [HurricanGame/Hurrican#49]
Hi there, @drfiemost 

Since the introduction of the additional CRT effects, performance on the Pi4 has decreased noticeably (I am not talking about my previous performance drop support, which comes from MESA).

So, would it be possible to have shaders without those additional effects? Something like `--crt-light` or similar.

Thanks

**Comment by drfiemost** [comment]
Added new options to individually enable CRT effects. `--crt` still enables all effects as before.

         --scanlines      : CRT effects: enable scanlines
         --colorbleed     : CRT effects: enable color bleeding
         --screencurve    : CRT effects: enable screen curvature
         --screennoise    : CRT effects: enable screen noise

See #50

**Comment by vanfanel** [comment]
Perfect! Works great!
Without noise effect, performance is where it was a year ago
