### ISSUE TITLE
Black screen on Raspberry Pi 4

### ISSUE THREAD

**Issue by vanfanel** [HurricanGame/Hurrican#53]
Hi there again, @drfiemost 

Since you did some final touches to the shader effect splitting code yesterday, I have rebuilt latest sources on the Pi4, and now, if I add --crt, -C or any of the CRT effects (like --colorbleed, --scanlines, etc) I get a black screen.

With no CRT effects,  the game runs normally.

**Comment by drfiemost** [comment]
> A log from an executable built with `-DCMAKE_BUILD_TYPE=Debug`? 

This, it will print the shader source and show possible errors.
But before recompiling you can check the file `data/shaders/100/shader_render.frag` and see if it's corrupted. The original for reference: https://github.com/HurricanGame/Hurrican/blob/master/Hurrican/data/shaders/100/shader_render.frag

**Comment by vanfanel** [comment]
@drfiemost Ok, re-copying the **data** dir from git made it work as expected...
How could corruption have happened? Strange thing. And worrying too.

**Comment by drfiemost** [comment]
Good. Maybe I've messed up by force pushing some changes, should be more careful in the future.
