### ISSUE TITLE
Remove obsolete Unrar support

### ISSUE THREAD

**Issue by IntinteDAO** [HurricanGame/Hurrican#54]
Hi. I noticed that in the Hurrican source code there is code responsible for unpacking RAR files. I'm wondering if this code is needed or if it's code that should be removed, as I haven't seen any RAR files in the project. In addition, I moved the source files of the code responsible for unpacking to another location and the code built without issue and works without problem.

I suspect it is some old, unused code that can be removed from the repository, but you guys have more knowledge about this (I suspect).

**Comment by Nils75owo** [comment]
It would need some fixing for it to work again. I have tinkered with it for about 1 hour now and there were some issues with it still using "the old filesystem" and stuff like ```LoadFileToMemory``` in ```SDL_port.cpp``` ignoring the unrarlib option.

**Comment by Nils75owo** [comment]
The library `urarlib` only supports RAR v2.0 and was discontinued decades ago.
The feature is completely broken and would need to be rewritten from scratch.

I think the feature should be:
1. removed to make the code a bit cleaner and to remove one of the 3rd party dependencies.
2. be completely reworked and replaced by a bit more modern alternative (like miniz).

I think it would make sense to remove it and if someone needs this feature I could add it back.

**Comment by drfiemost** [comment]
You're right, this is almost useless nowadays.
Renaming the issue.

**Comment by drfiemost** [comment]
Closing this. If someone is interested in a data packing feature just open a new issue.
