### ISSUE TITLE
Using STL

### ISSUE THREAD

**Issue by bufalo1973** [HurricanGame/Hurrican#61]
I've been taking a look at the code and I'm asking, why use the "C list" way instead of using STL containers? First example is in GegnerClass. I think it would make the code easier (and shorter?) to maintain using STL.

**Comment by drfiemost** [comment]
The original code is quite old, there have been some efforts to modernize it but there is still room for improvement.

I think I gave a try at converting it into a std::list or something but didn't succeed for some reason and gave up.

**Comment by drfiemost** [comment]
The enemies are done, next steps are projectiles and particles.

**Comment by drfiemost** [comment]
It seems we got rid of custom lists now. Thanks to @Nils75owo
